"""Versioned HTTP contracts shared by API routes and client fixtures."""

from thoughtpins.api_contracts.account import (
    SAFETY_REPORT_CATEGORIES,
    SAFETY_REPORT_TARGET_TYPES,
    AccountDeleteRequest,
    DeviceRegistrationRequest,
    DeviceResponse,
    DevicesPageResponse,
    InviteRedeemRequest,
    InviteRequestResponse,
    InviteRequestSubmission,
    InviteStatusResponse,
    LegalAcceptanceRequest,
    PasswordSetRequest,
    PasswordSetResponse,
    SafetyReportRequest,
    SafetyReportResponse,
    SessionResponse,
    SessionsPageResponse,
    SignInMethodsResponse,
)
from thoughtpins.api_contracts.chat import (
    AskResponse,
    ChatConversationResponse,
    ChatConversationsPageResponse,
    ChatMessageResponse,
    ChatMessagesPageResponse,
    ChatRequest,
    ChatResponse,
)
from thoughtpins.api_contracts.common import COMMON_ERROR_RESPONSES, ErrorDetail, ErrorEnvelope
from thoughtpins.api_contracts.library import (
    LibraryIngestRequest,
    LibraryIngestResponse,
    UploadIngestRequest,
    UploadIngestResponse,
    VaultImportOperationRequest,
    VaultImportPreviewItem,
    VaultImportRequest,
    VaultImportResponse,
    VaultImportSessionResponse,
    VaultUploadChunkRequest,
    VaultUploadCreateRequest,
)
from thoughtpins.api_contracts.stats import StatsResponse
from thoughtpins.api_contracts.voice import (
    VoiceArchiveConsentRequest,
    VoiceArchiveDeleteRequest,
    VoiceArchiveDeleteResponse,
    VoiceArchiveStatusResponse,
)

__all__ = [
    "AccountDeleteRequest",
    "AskResponse",
    "ChatConversationResponse",
    "ChatConversationsPageResponse",
    "ChatMessageResponse",
    "ChatMessagesPageResponse",
    "ChatRequest",
    "ChatResponse",
    "COMMON_ERROR_RESPONSES",
    "DeviceRegistrationRequest",
    "DeviceResponse",
    "DevicesPageResponse",
    "ErrorDetail",
    "ErrorEnvelope",
    "InviteRedeemRequest",
    "InviteRequestResponse",
    "InviteRequestSubmission",
    "InviteStatusResponse",
    "LegalAcceptanceRequest",
    "LibraryIngestRequest",
    "LibraryIngestResponse",
    "PasswordSetRequest",
    "PasswordSetResponse",
    "SAFETY_REPORT_CATEGORIES",
    "SAFETY_REPORT_TARGET_TYPES",
    "SafetyReportRequest",
    "SafetyReportResponse",
    "SessionResponse",
    "SessionsPageResponse",
    "SignInMethodsResponse",
    "StatsResponse",
    "UploadIngestRequest",
    "UploadIngestResponse",
    "VaultImportOperationRequest",
    "VaultImportPreviewItem",
    "VaultImportRequest",
    "VaultImportResponse",
    "VaultImportSessionResponse",
    "VaultUploadChunkRequest",
    "VaultUploadCreateRequest",
    "VoiceArchiveConsentRequest",
    "VoiceArchiveDeleteRequest",
    "VoiceArchiveDeleteResponse",
    "VoiceArchiveStatusResponse",
]
