"""Verify that Python lock artifacts match the declared dependency graph."""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
UV_COMMAND = [sys.executable, "-m", "uv"]
PRODUCTION_LOCK = ROOT / "requirements-prod.lock"
UV_CACHE = ROOT / ".tmp" / "uv-cache"


def main() -> int:
    if not (ROOT / "uv.lock").is_file():
        print("Dependency lock check failed: uv.lock is missing")
        return 1
    if not PRODUCTION_LOCK.is_file():
        print("Dependency lock check failed: requirements-prod.lock is missing")
        return 1

    UV_CACHE.mkdir(parents=True, exist_ok=True)
    uv_env = os.environ.copy()
    uv_env["UV_CACHE_DIR"] = str(UV_CACHE)
    lock_check = subprocess.run(
        [*UV_COMMAND, "lock", "--check"],
        cwd=ROOT,
        env=uv_env,
        check=False,
        text=True,
    )
    if lock_check.returncode != 0:
        print("Dependency lock check failed: uv.lock is stale")
        return 1

    exported = subprocess.run(
        [
            *UV_COMMAND,
            "export",
            "--frozen",
            "--no-dev",
            "--extra",
            "workers",
            "--no-emit-project",
            "--format",
            "requirements-txt",
        ],
        cwd=ROOT,
        env=uv_env,
        check=False,
        capture_output=True,
        text=True,
    )
    if exported.returncode != 0:
        print("Dependency lock check failed: production export could not be generated")
        if exported.stderr:
            print(exported.stderr.strip()[:500])
        return 1

    expected = _without_generator_header(PRODUCTION_LOCK.read_text(encoding="utf-8"))
    actual = _without_generator_header(exported.stdout)
    if expected != actual:
        print("Dependency lock check failed: requirements-prod.lock is stale")
        print("Regenerate it with:")
        print(
            "  uv export --frozen --no-dev --extra workers --no-emit-project "
            "--format requirements-txt --output-file requirements-prod.lock"
        )
        return 1

    print("Dependency lock check passed: uv.lock and requirements-prod.lock are current.")
    return 0


def _without_generator_header(text: str) -> str:
    lines = text.replace("\r\n", "\n").splitlines()
    if lines and lines[0].startswith("# This file was autogenerated by uv"):
        lines = lines[2:]
    return "\n".join(lines).strip() + "\n"


if __name__ == "__main__":
    raise SystemExit(main())
